head/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('profile/', views.profile, name='profile'),

]

top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('head/', include(('head.urls', 'head'), namespace='head')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views

urlpatterns =[
   path('sign_up/', views.sign_up, name='sign_up')
]

head/models.py
from django.db import models
from django.contrib.auth.models import User


class SliderImage(models.Model):
    image = models.ImageField()

    def __str__(self):
        return f"Image #{self.pk}"


GENDER_CHOICE = [
    ('men', 'men'),
    ('female', 'female')
]


class User(models.Model):
    username = models.CharField(max_length=255)
    birthday = models.DateTimeField()
    email = models.EmailField()
    password = models.CharField(max_length=255)
    gender = models.CharField(max_length=255, choices=GENDER_CHOICE)


class Profile(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    about = models.TextField()
    job = models.CharField(max_length=255)
    hobbies = models.CharField(max_length=255)
    image = models.ImageField()

users/models.py
from django.db import models


users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .bulma_mixin import BulmaMixin

class SignUpForm(BulmaMixin, UserCreationForm):
    username = forms.CharField(label='Придумайте никнейм')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Придумайте пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Повторите пароль')
    email = forms.CharField(label='Введите свою почту')

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']

head/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth import login, logout
from .forms import SignInForm

def home(request):
    action = request.GET.get('action')
    confirm_login = False
    if action == 'log_in':
        confirm_login = True
    form = SignInForm(data=request.POST or None)
    if form.is_valid():
        user = form.get_user()
        login(request, user)
        return redirect('head:profile')
    return render(request, 'home.html', {'form': form, 'confirm_login': confirm_login})

def profile(request):
    return render(request, 'profile.html', {})



def sign_out(request):
    logout(request)
    return redirect('head:home')

users/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, logout

def sign_up(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
       form.save()
       return redirect('head:home')
    return render(request, 'sign_up.html', {'form': form})

head/templates/base_layout.html
{% load static from static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'static/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body>
{% block nav %}
{% endblock %}

{% block content %}

{% endblock %}
</body>

head/templates/home.html
{% extends 'base_layout.html' %}
{% load static %}
{% block nav %}
    <nav role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'head:home' %}">
                <span class="title"
                      style="color: orangered; font-family: 'Academy Engraved LET'; font-size: 60px; padding: 2px;">CD</span>
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
               data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start" style="font-size: 22px; font-weight: bold; font-family: 'Comic Sans MS'">

                <a class="navbar-item" style="color: darkorange">
                    О нас
                </a>

                <a class="navbar-item" style="color: darkorange">
                    Контакты
                </a>

                <a class="navbar-item" style="color: darkorange">
                    FAQ
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link" style="color: darkorange">
                        Советы по безопастности
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" style="color: darkorange">
                            Правила сообщества
                        </a>
                        <a class="navbar-item" style="color: darkorange">
                            Центр безопастности и разроботки
                        </a>
                        <a class="navbar-item" style="color: darkorange">
                            Предложения и жалобы
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" style="color: darkorange">
                            Безопастность
                        </a>
                    </div>
                </div>
            </div>

            <div class="navbar-end">
                {#                {% if not user.is_authenticated %}#}
                <div class="navbar-item">
                    <div class="buttons">
                        <div class="button is-warning" style="margin: 3px">
                            <a href="{% url 'users:sign_up' %}" style="color: coral">Создать аккаунт</a>
                        </div>
                    </div>
                </div>
                {#                {% endif %}#}
            </div>
        </div>
    </nav>
{% endblock %}
<!-- {% block slider %}
<div class="container-slide">
    <div id="carousel-demo" class="carousel">
        {% for slide in slides %}
        <div class="item-1">
            <img src="{{ slide.image.url }}" alt="" class="slide-img">
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %} -->

{% block content %}
    <section class="section">
        <div class="container">
            <div class="title has-text-centered">
                <h1 style="color: orangered; font-family: 'Academy Engraved LET'; font-size: 170px; margin: 20px; padding: 1px; margin-top: 50px">
                    ClICKDATE</h1>
            </div>
            <div class="subtitle" style="text-align: center; font-family: 'Brush Script MT'; color: lightgoldenrodyellow; font-size: 80px; padding: 1px">
                <p>"Любовь и точка!"</p>
            </div>
            {#            <button class="button">#}
            {#                <a href="{% url 'users:sign_up' %}">Создать аккаунт</a>#}
            {#            </button>#}
            <div class="enter has-text-centered" style="margin-top: 40px; padding: 5px">
                <a href="{% url 'head:home' %}?action=log_in" class="button is-danger is-large">Войти в аккаунт</a>
            </div>
            <div class="modal {% if confirm_login %} is-active {% endif %}">
                <div class="modal-background"></div>
                <div class="modal-content">

                    <div class="columns is-centered mt-3">
                        <div class="column is-6">
                            <div class="box has-background" style="background-color: lavenderblush">
                                <form method="post">
                                    <div class="has-text-right">
                                        <a href="{% url 'head:home' %}">
                                            <ion-icon class="is-size-3" name="close-outline"></ion-icon>
                                        </a>
                                    </div>
                                    <div class="title is-2 has-text-centered" style="font-family: 'Comic Sans MS'">
                                        Вход
                                    </div>
                                    {% csrf_token %}
                                    {% for field in form %}
                                        <div class="field">
                                            <label for="{{ field.id_for_label }}" class="label">
                                                {{ field.label }}
                                            </label>
                                            <div class="control">
                                                {{ field }}
                                            </div>
                                        </div>
                                    {% endfor %}

                                    {% if form.errors %}
                                        <ul>
                                            {% for error in form.errors.values %}
                                                <li class="has-text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    <div class="has-text-centered">
                                        <button class="button is-danger is-fullwidth">
                                            Войти
                                        </button>
                                    </div>
                                    <br>
                                    <div class="has-text-centered">
                                        <p>У вас нет аккаунта?</p>
                                        <div class="button">
                                            <a href="{% url 'users:sign_up' %}">Создать аккаунт</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/sign_up.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <div class="columns is-centered mt-3">
        <div class="column is-4">
            <div class="box" style="background-color: lavenderblush">
                <form method="post">
                    <div class="has-text-right">
                        <a href="{% url 'head:home' %}">
                            <ion-icon class="is-size-3" name="close-outline"></ion-icon>
                        </a>
                    </div>
                    <div class="title is-2 has-text-centered" style="font-family: 'Comic Sans MS'">
                        Регистрация
                    </div>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">
                                {{ field.label }}
                            </label>
                            <div class="control">
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}

                    {% if form.errors %}
                        <ul>
                            {% for error in form.errors.values %}
                                <li class="has-text-danger">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="has-text-centered">
                        <button class="button is-danger is-fullwidth">
                            Отправить
                        </button>
                        <br>
                        <button class="button is-warning is-fullwidth" type="submit">
                            <a href="{% url 'head:home' %}">Назад</a>
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}